/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICrowdfunding,
  ICrowdfundingInterface,
} from "../../../contracts/interfaces/ICrowdfunding";

const _abi = [
  {
    inputs: [],
    name: "withdrawForAll",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ICrowdfunding__factory {
  static readonly abi = _abi;
  static createInterface(): ICrowdfundingInterface {
    return new Interface(_abi) as ICrowdfundingInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ICrowdfunding {
    return new Contract(address, _abi, runner) as unknown as ICrowdfunding;
  }
}
