/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IEvaluationInterface extends Interface {
  getFunction(
    nameOrSignature: "selectEvaluators" | "setSelectedEvaluators"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "selectEvaluators",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setSelectedEvaluators",
    values: [AddressLike[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "selectEvaluators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSelectedEvaluators",
    data: BytesLike
  ): Result;
}

export interface IEvaluation extends BaseContract {
  connect(runner?: ContractRunner | null): IEvaluation;
  waitForDeployment(): Promise<this>;

  interface: IEvaluationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  selectEvaluators: TypedContractMethod<[], [boolean], "nonpayable">;

  setSelectedEvaluators: TypedContractMethod<
    [_selectedEvaluators: AddressLike[]],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "selectEvaluators"
  ): TypedContractMethod<[], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "setSelectedEvaluators"
  ): TypedContractMethod<
    [_selectedEvaluators: AddressLike[]],
    [void],
    "nonpayable"
  >;

  filters: {};
}
