/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ICrowdfunding } from "./ICrowdfunding";
export type { IEvaluation } from "./IEvaluation";
export type { IHypercerts } from "./IHypercerts";
export type { INLRead } from "./INLRead";
export type { IPUSHCommInterface } from "./IPUSHCommInterface";
export type { IVRFv2Consumer } from "./IVRFv2Consumer";
