/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IVRFv2ConsumerInterface extends Interface {
  getFunction(
    nameOrSignature: "requestRandomWords" | "setPermittedEvaluator"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "requestRandomWords",
    values: [BigNumberish, AddressLike, AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setPermittedEvaluator",
    values: [AddressLike, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "requestRandomWords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPermittedEvaluator",
    data: BytesLike
  ): Result;
}

export interface IVRFv2Consumer extends BaseContract {
  connect(runner?: ContractRunner | null): IVRFv2Consumer;
  waitForDeployment(): Promise<this>;

  interface: IVRFv2ConsumerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  requestRandomWords: TypedContractMethod<
    [
      _numWords: BigNumberish,
      _evaluatorContract: AddressLike,
      _evaluators: AddressLike[]
    ],
    [bigint],
    "nonpayable"
  >;

  setPermittedEvaluator: TypedContractMethod<
    [_evaluator: AddressLike, _permitted: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "requestRandomWords"
  ): TypedContractMethod<
    [
      _numWords: BigNumberish,
      _evaluatorContract: AddressLike,
      _evaluators: AddressLike[]
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPermittedEvaluator"
  ): TypedContractMethod<
    [_evaluator: AddressLike, _permitted: boolean],
    [void],
    "nonpayable"
  >;

  filters: {};
}
