/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace NLRead {
  export type ProjectStruct = {
    id: BigNumberish;
    amount: BigNumberish;
    projectTime: BigNumberish[];
    info: string;
    status: BigNumberish;
    crowdfunding: AddressLike;
    evaluation: AddressLike;
    creator: AddressLike;
  };

  export type ProjectStructOutput = [
    id: bigint,
    amount: bigint,
    projectTime: bigint[],
    info: string,
    status: bigint,
    crowdfunding: string,
    evaluation: string,
    creator: string
  ] & {
    id: bigint;
    amount: bigint;
    projectTime: bigint[];
    info: string;
    status: bigint;
    crowdfunding: string;
    evaluation: string;
    creator: string;
  };
}

export interface NLReadInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getAllProjectsByStatus"
      | "getAllProjectsByUser"
      | "getAllProjectsByUserStatus"
      | "getProjectByUser"
      | "getUsers"
      | "hypercerts"
      | "isUser"
      | "portfolios"
      | "pushComm"
      | "treasury"
      | "users"
      | "vrfConsumer"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ProjectCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "getAllProjectsByStatus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllProjectsByUser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllProjectsByUserStatus",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProjectByUser",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getUsers", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "hypercerts",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "isUser", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "portfolios",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "pushComm", values?: undefined): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(functionFragment: "users", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "vrfConsumer",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "getAllProjectsByStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllProjectsByUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllProjectsByUserStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProjectByUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getUsers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hypercerts", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isUser", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "portfolios", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pushComm", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "users", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "vrfConsumer",
    data: BytesLike
  ): Result;
}

export namespace ProjectCreatedEvent {
  export type InputTuple = [
    projectId: BigNumberish,
    amount: BigNumberish,
    projectTime: BigNumberish[],
    info: string,
    status: BigNumberish,
    crowdfunding: AddressLike,
    evaluation: AddressLike,
    creator: AddressLike
  ];
  export type OutputTuple = [
    projectId: bigint,
    amount: bigint,
    projectTime: bigint[],
    info: string,
    status: bigint,
    crowdfunding: string,
    evaluation: string,
    creator: string
  ];
  export interface OutputObject {
    projectId: bigint;
    amount: bigint;
    projectTime: bigint[];
    info: string;
    status: bigint;
    crowdfunding: string;
    evaluation: string;
    creator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface NLRead extends BaseContract {
  connect(runner?: ContractRunner | null): NLRead;
  waitForDeployment(): Promise<this>;

  interface: NLReadInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAllProjectsByStatus: TypedContractMethod<
    [_status: BigNumberish],
    [NLRead.ProjectStructOutput[]],
    "view"
  >;

  getAllProjectsByUser: TypedContractMethod<
    [_user: AddressLike],
    [NLRead.ProjectStructOutput[]],
    "view"
  >;

  getAllProjectsByUserStatus: TypedContractMethod<
    [_user: AddressLike, _status: BigNumberish],
    [NLRead.ProjectStructOutput[]],
    "view"
  >;

  getProjectByUser: TypedContractMethod<
    [_user: AddressLike, _projectId: BigNumberish],
    [NLRead.ProjectStructOutput],
    "view"
  >;

  getUsers: TypedContractMethod<[], [string[]], "view">;

  hypercerts: TypedContractMethod<[], [string], "view">;

  isUser: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  portfolios: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  pushComm: TypedContractMethod<[], [string], "view">;

  treasury: TypedContractMethod<[], [string], "view">;

  users: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  vrfConsumer: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAllProjectsByStatus"
  ): TypedContractMethod<
    [_status: BigNumberish],
    [NLRead.ProjectStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAllProjectsByUser"
  ): TypedContractMethod<
    [_user: AddressLike],
    [NLRead.ProjectStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAllProjectsByUserStatus"
  ): TypedContractMethod<
    [_user: AddressLike, _status: BigNumberish],
    [NLRead.ProjectStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProjectByUser"
  ): TypedContractMethod<
    [_user: AddressLike, _projectId: BigNumberish],
    [NLRead.ProjectStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUsers"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "hypercerts"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isUser"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "portfolios"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "pushComm"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "users"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "vrfConsumer"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "ProjectCreated"
  ): TypedContractEvent<
    ProjectCreatedEvent.InputTuple,
    ProjectCreatedEvent.OutputTuple,
    ProjectCreatedEvent.OutputObject
  >;

  filters: {
    "ProjectCreated(uint256,uint256,uint256[],string,uint256,address,address,address)": TypedContractEvent<
      ProjectCreatedEvent.InputTuple,
      ProjectCreatedEvent.OutputTuple,
      ProjectCreatedEvent.OutputObject
    >;
    ProjectCreated: TypedContractEvent<
      ProjectCreatedEvent.InputTuple,
      ProjectCreatedEvent.OutputTuple,
      ProjectCreatedEvent.OutputObject
    >;
  };
}
